builds create prompt ui
MilcahHalili/litkit-ui-preview pull request #68
Opened 2022-01-29 00:47 UTC by H-b8

Builds UI for `pages/prompt/new.js`.

2022-01-29 20:19 UTC, MilcahHalili requested changes
This is a great start, @H-b8! Can you also build out the api route so that, on click of the submit button, a new prompt is created in the database?

2022-01-30 07:58 UTC, H-b8 commented
- Built off of the `api/prompt/create` you started and have a successful post to db. Test @ /prompt/new
- Refactored code in a few places to get rid of warnings in the console
- Style adjustments
- Refactored Prompt component to show author on index page
- Refactored `prompt/[id]` page

2022-01-30 21:35 UTC, MilcahHalili requested changes
Amazing! Excellent work, @H-b8. Just a couple tiny change requests, and then we'll be good to go.

2022-01-30 21:35 UTC, MilcahHalili commented on components/Prompt.js
> +      <p className={Styles.instructorName}>By {authorName || 'Unknown Instrcutor'}</p>
Typo in `Instructor`!

2022-01-30 21:35 UTC, MilcahHalili commented on pages/api/prompt/create.js
> +          authorId: user.id,
Thanks for removing the hard-coded value/making this dynamic!

2022-01-30 21:35 UTC, MilcahHalili commented on pages/prompt/[id].js
> +    setData(res);
Ooo this is so much cleaner, tysm!

2022-01-30 21:35 UTC, MilcahHalili commented on pages/prompt/[id].js
> +    console.log('yes!');
Lol we can remove this console log now, thanks!

2022-01-30 21:35 UTC, MilcahHalili commented on pages/prompt/[id].js
> -import ReactMarkdown from "react-markdown"
Nice!

2022-01-30 21:53 UTC, H-b8 commented
Good eye @MilcahHalili ! Console removed and typo fixed 😄

2022-01-31 01:38 UTC, MilcahHalili approved these changes
Well done!

2022-01-31 01:38 UTC, merged